version: "3.4"
services:
  mm-website:
    build:
      context: .
      dockerfile: Dockerfile.prod.yml
    container_name: mm-website
    ports:
      - "80:5000"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=production
      - TWILIO_ACCOUNT_ID=${TWILIO_ACCOUNT_ID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
    restart: always
