FROM node:10

# working dir
WORKDIR /usr/src/app

# install dependencies from both package.json and package-lock.json
COPY package*.json ./

# for prod RUN npm install --only=production
RUN npm install

# bundle
# COPY . .

EXPOSE 5000

# start server
CMD ["npm", "start"]
