# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/Maritza-Mancillas # name of the dir we use in circle ci
    docker:
      - image: circleci/node:8.11
    steps:
      - checkout # clones the repo
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install-dependencies
          command: npm install
      # TODO run unit tests here
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Deploy app to Digital Ocean Server via Docker
          command: |
            tar -cvf ~/Maritza-Mancillas.tar ~/Maritza-Mancillas &&
            scp -o StrictHostKeyChecking=no -r ~/Maritza-Mancillas.tar $SSH_USER@$SSH_HOST:/root/ &&
            ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "tar xf /root/Maritza-Mancillas.tar &&
              cd /root/home/circleci/Maritza-Mancillas/ &&
              ./.circle_deployer.sh"
